In [2]:
from google.colab import files
uploaded = files.upload()

Saving spam.csv to spam.csv


In [74]:
import pandas as pd
df = pd.read_csv("spam.csv")
df.head(2)

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...

In [75]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [76]:
# Looks like an imbalanced dataset

In [77]:
df['spam'] = df['Category'].apply(lambda x: 1 if x == 'spam' else 0)
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [78]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [79]:
X_train.shape

(4457,)

In [80]:
X_test.shape

(1115,)

In [81]:
type(X_train)

pandas.core.series.Series

In [19]:
X_train[:4][1684]

'Already am squatting is the new way of walking'

In [20]:
type(y_train)

pandas.core.series.Series

In [21]:
y_train[:4]

1684    0
4071    0
2942    0
4807    0
Name: spam, dtype: int64

In [37]:
from sklearn.feature_extraction.text import CountVectorizer

v= CountVectorizer()
X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 59658 stored elements and shape (4457, 7756)>

In [33]:
X_train_cv.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [35]:
X_train_cv.shape # 7756 unique words

(4457, 7756)

In [44]:
v.get_feature_names_out()[6124]

'shoppin'

In [50]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

import numpy as np
np.where(X_train_np[0]!=0)

(array([ 938,  950, 3762, 4782, 4920, 6443, 6835, 7372, 7421]),)

In [55]:
X_train[:4]

1684       Already am squatting is the new way of walking
4071    Ok i wont call or disturb any one. I know all ...
2942    My supervisor find 4 me one lor i thk his stud...
4807          Call me when u finish then i come n pick u.
Name: Message, dtype: object

In [60]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [63]:
X_test_cv = v.transform(X_test)

In [68]:
y_pred = model.predict(X_test_cv)

from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99       963
           1       0.99      0.89      0.93       152

    accuracy                           0.98      1115
   macro avg       0.98      0.94      0.96      1115
weighted avg       0.98      0.98      0.98      1115



In [71]:
emails = [
    'Hey, Mohan can we watch movie tommorow together?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])

In [85]:
from sklearn.pipeline import Pipeline

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

clf = Pipeline([
    ('v' ,CountVectorizer()),
    ('nb', MultinomialNB())
])

clf.fit(X_train, y_train)

Pipeline(steps=[('v', CountVectorizer()), ('nb', MultinomialNB())])

In [87]:
print(classification_report(y_test, clf.predict(X_test)))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99       949
           1       0.98      0.89      0.93       166

    accuracy                           0.98      1115
   macro avg       0.98      0.94      0.96      1115
weighted avg       0.98      0.98      0.98      1115

